# Generated by Django 2.1.3 on 2018-12-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/%Y/%m/%d/'),
        ),
    ]
